### ISSUE TITLE
firefox-66-r1 fails to build

### ISSUE THREAD

**Issue by MageSlayer** [MageSlayer/paludis-gentoo-patches#15]
firefox-66.0-r1 will not compile with paludis. It compiles fine with portage. The failure comes at the start of the compile phase showing an autoconf issue. The real issue is that we are getting corruption in the PATH assignment is various config files. The source of the problem is loadsaveenv file in the temp directory which shows
PATH=$' \E[32;01m*\E[0m Will use LLVM slot 8!\n/usr/lib/llvm/8/bin:/var/tmp/paludis/www-client-firefox-66.0-r1/temp//python3.6/bin:/usr/libexec/paludis/utils/0:/usr/libexec/paludis/utils/1:/usr/libexec/paludis/utils/2:/usr/libexec/paludis/utils/3:/usr/libexec/paludis/utils/4:/usr/libexec/paludis/utils/5:/usr/libexec/paludis/utils/6:/usr/libexec/paludis/utils:/usr/bin:/usr/sbin:/bin:/sbin:/usr/lib/llvm/8/bin:/usr/lib/llvm/7/bin:/usr/lib/llvm/6/bin:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/opt/vmware/bin:/opt/cuda/bin:/opt/cuda/libnvvp'

The \E[32;01m*\E[0m Will use LLVM slot 8!\n string should not be there and if manually removed before config phase the build completes.

**Comment by kdudka** [comment]
Same here with `www-client/firefox-66.0.2` and LLVM in slot 6.  Per suggestion above, `cave resolve ... --abort-at-phase configure`, manual fixup of `/var/tmp/paludis/www-client-firefox-66.0.2/temp/loadsaveenv` and `cave resolve ... --skip-until-phase configure` made the build start.

**Comment by styrsven** [comment]
My findings on this issue:
in llvm.eclass, the llvm_pkg_setup function adds the llvm path to the PATH variable. The path is the return value from get_llvm_prefix.
get_llvm_prefix uses llvm_check_deps from the ebuild to find which LLVM version the ebuild needs.
Unfortunately, the einfo call in llvm_check_deps contaminates stdout with its text, so that the text (including control characters) gets appended to the path along with the llvm path.

The reason other ebuilds that refers to LLVM in a similar way is probably that autoconf gets used in a way that triggers the error just for firefox. I checked thunderbird and the path gets contaminated the same way, but it builds just fine.

I can think of two possible causes for this issue:
1. My main hypothesis is that the difference is caused by the fact that einfo is implemented differently in portage (python) vs paludis (bash).
2. A wild unfounded guess would be that it just happens to work in portage because the error is ignored.

Both of those possible causes is beyond my capacity  to try to fix.

My personal workaround is to just comment out the einfo in the ebuild.

**Comment by MageSlayer** [comment]
Thanks for your investigation.
I am pretty sure, that your idea about einfo is correct.

BTW. 
EAPI7 design also contains:

> Output commands no longer pollute stdout
> The output channel for commands einfo, elog, etc. was undefined in previous EAPIs. As a result, the  messages were frequently output into stdout. While this normally is not a problem, it limits the ability of using them in eclass functions that might be called via command substitution. With the newly-added eqawarn this problem becomes even more likely.
> Starting with EAPI 7, those commands are guaranteed not to output to stdout.

Looks like the same logic should be retrofitted into earlier EAPIs :(

**Comment by MageSlayer** [comment]
Firefox ebuild should emerge now.
Please test and close if ok.

**Comment by kdudka** [comment]
I can confirm that `www-client/firefox-66.0.3` builds fine with 9a215e4f2d00edf8df5d92a14b29dc1fe0e94a83 but I do not have privileges to close this issue.  Thank you for fixing it!

**Comment by hlandgarten** [comment]
confirmed bug fixed

**Comment by MageSlayer** [comment]
Ok, thanks.
