### ISSUE TITLE
Add Ionic as a maintainer?

### ISSUE THREAD

**Issue by bqv** [MageSlayer/paludis-gentoo-patches#42]
Hi @MageSlayer 

Since this has been quiet some time, maybe it's worth adding @Ionic as a maintainer so the project keeps moving? At first glance it seems dead, at this point, but those PRs are just waiting, and the eapi8 branch is close

**Comment by negril** [comment]
Could you add me as well?

I have more changes on top of Ionics and my work and rebased it on top of the current upstream master. See https://github.com/negril/paludis/tree/gentoo/build
or https://gitlab.exherbo.org/negril/paludis/-/tree/gentoo/build .

The eapi8 branch is at https://gitlab.exherbo.org/negril/paludis/-/tree/gentoo/feature/eapi8 .

**Comment by thesamesam** [comment]
I'm open to it eventually going back into ::gentoo if we can find good maintainers for it, too,

**Comment by thesamesam** [comment]
Doing the fixes both you and @ionic have been doing already, having a single repo where we have all the patches, and  being reasonably responsive to bugs on Bugzilla. In this case, what I meant was "we really want a single "upstream" for a working Paludis", and it's a lot easier if the two people actively workign on it have access to the same repo.

**Comment by MageSlayer** [comment]
@negril 
Invited.

**Comment by Ionic** [comment]
Thanks. I've been oddly quiet on this mainly due to work reasons. Just plainly had not time to work on it (or, for that matter, even update my machine.)

My vacation is coming up at the end of December and January, so I hope that I'll be able to work on it in a more focused way.

> My idea was to be as close to upstream paludis as possible and then have our own branch onto of it. Hence the repo on their gitlab. We could use that or something on here. If and when Ionic has input we could figure that out.

I mostly agree with that (which, btw, is why I want to keep changes minimal and didn't integrate your test suite mechanic changes - while I do like them personally, they aren't really changing anything other than making adding tests more easy and using a cleaner, newer API). I'm not a huge fan of calling the Gentoo-part of paludis a fork - my goal would be to integrate our changes back into the main paludis repository. While it doesn't really have any implications for exherbo itself, it would make maintaining paludis a lot easier, since we wouldn't have to constantly rebase against their main branch. So far, they haven't thrown out support for Gentoo-style EAPIs and ebuilds, which gets my hopes up that they would eventually merge good-quality code back in, as long as it doesn't break their use cases.
